### ISSUE TITLE
[Bug]: DNS OVH challenge does not delete TXT record after challenge is completed

### ISSUE THREAD

**Issue by javiku** [certbot/certbot#10492]
### OS

Ubuntu 22.04, but certbot running on docker container

### Installation method

Runing on docker container (image certbot/dns-ovh:v5.1.0)

### Certbot Version

5.1.0

### What happened?

When creating and renewing certificates with OVH DNS challenges, the **certificates are created/renewed correctly**, but the **challenge TXT DNS records are not deleted**. This happens all the time with OVH DNS credentials configured following both ways explained in the [documentation](https://certbot-dns-ovh.readthedocs.io/en/stable/#credentials).

I already checked issue #7773 but this doesn't seem to be the same problem.

### Expected behavior

I expect certbot to delete the challenge TXT DNS records once the certificate has been issued/renewed.

### Relevant log output

```shell
In the following section of the logs, we can see that the ID of the record to be deleted is obtained correctly, but then the list_records and delete_records lists are *empty*.


2025-11-20 09:01:32,602:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2025-11-20 09:01:32,727:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2025-11-20 09:01:32,787:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 None
2025-11-20 09:01:32,842:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/myzone.cloud/status HTTP/1.1" 200 None
2025-11-20 09:01:32,901:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/myzone.cloud/record?fieldType=TXT&subDomain=_acme-challenge.brether HTTP/1.1" 200 12
2025-11-20 09:01:32,966:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/myzone.cloud/record/5390301234 HTTP/1.1" 200 None
2025-11-20 09:01:32,967:DEBUG:lexicon._private.providers.ovh:list_records: []
2025-11-20 09:01:32,967:DEBUG:lexicon._private.providers.ovh:delete_records: []
2025-11-20 09:01:33,052:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "POST /1.0/domain/zone/myzone.cloud/refresh HTTP/1.1" 200 4
2025-11-20 09:01:33,054:DEBUG:lexicon._private.providers.ovh:delete_record: True
```

**Comment by javiku** [comment]
Trying to debug this, I believe this is related to https://github.com/dns-lexicon/dns-lexicon/pull/65.

**Comment by marek1712** [comment]
Would there be an option NOT to delete the TXT record(s)?
Reason: I don't want to grant API user too extensive permissions. It's possible with **Posh-ACME**, see [LINK](https://poshac.me/docs/v4/Plugins/OVH/#write-to-specific-records).

**Comment by javiku** [comment]
> Would there be an option NOT to delete the TXT record(s)? Reason: I don't want to grant API user too extensive permissions. It's possible with **Posh-ACME**, see [LINK](https://poshac.me/docs/v4/Plugins/OVH/#write-to-specific-records).

I believe your comment is not related to this issue, you should open a separate one.

**Comment by Nakun1** [comment]
Same issue here.

It’s annoying because at OVH, the '_acme-challenge' records break wildcards. I had to manually re-add all our subdomains to our DNS in a rush.

**Comment by chikeb-aymen** [comment]
Same issue here, there is multiple acme_challenge and OVH not delete record after validation and mainly in wildcard domain

**Comment by ohemorange** [comment]
I believe this is fixed by that lexicon issue linked above. It hasn't yet been released though, so it may be helpful to direct comments requesting that release over there.

**Comment by benjaminmal** [comment]
Still happening here with brand new credentials, `DELETE /domain/zone/*` rights (and the other), we had reach the maximum limit of DNS records (about 1300) and get this error since:

> Error adding TXT record: 400 Client Error: Bad Request for url: https://eu.api.ovh.com/1.0/domain/zone/{domain}/record

Removing all `_acme-challenge` fix the 400 error from happening obviously.

**Comment by NeoXTof** [comment]
Same for me with certbot 5.3.1, no issue to create or renew certificates but the _acme-challenge are not deleted

The api access is properly defined according to certbot-dns-ovh documentation

> GET /domain/zone/*
> PUT /domain/zone/*
> POST /domain/zone/*
> DELETE /domain/zone/*

```
DEBUG:lexicon._private.providers.ovh:list_records: []
DEBUG:lexicon._private.providers.ovh:delete_records: []
DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "POST /1.0/domain/zone/<eredacted>/refresh HTTP/1.1" 200 4
DEBUG:lexicon._private.providers.ovh:delete_record: True
```

**Comment by chikeb-aymen** [comment]
Until now there is no fix from Certbot, I think we should find a proper solution for this case is better than waiting 👀

**Comment by NeoXTof** [comment]
I digged a little, even the ovh-python lib is having the same issue. If certbot is using it, the fix will need to come from this lib ... that seems to be abandonned

https://github.com/ovh/python-ovh/issues/124

**Comment by javiku** [comment]
As I mentioned right after creating the issue, I believe this stems from https://github.com/dns-lexicon/dns-lexicon/pull/65 and it's been fixed there a while ago now.

**Comment by guillaumesmo** [comment]
it has been fixed but the last release of dns-lexicon is v3.23.2 on Nov 14, 2025 - the fix will only come in the next release.

**Comment by NeoXTof** [comment]
I checked the fix, it's quite simple with 1 line to change in ovh.py https://github.com/dns-lexicon/dns-lexicon/commit/b6c25131fdabda342caa37cb21acda07ece8ff44

I'll give it a try while waiting for the official release

**Comment by 520gmail** [comment]
[](url)

**Comment by NeoXTof** [comment]
So, I changed the line 169 in the ovh.py file
replacing 
               ` if record["content"].lower() == content.lower()`
by 
               ` if record["content"].lower() in {content.lower(), f"\"{content.lower()}\""}`

 and I can confirm 2 points:
1. It's working , no more orphan TXT records in my OVH zone
2. Getting a new certificate and renewing is much faster !

Thanks @guillaumesmo for the fix ;)

**Comment by ohemorange** [comment]
Yes, by "it's fixed in lexicon" I did in fact mean there is a PR to fix it, and therefore whenever lexicon does a release then certbot can pull it in and it will be fixed here as well. If you would like that to happen sooner, I recommend joining the calls for a new lexicon release on [the relevant lexicon PR](https://github.com/dns-lexicon/dns-lexicon/pull/65).

**Comment by chikeb-aymen** [comment]
I tried using our custom Docker image with latest version of lexicon in our project, but it’s still not working:
```
FROM certbot/dns-ovh:latest
RUN pip install --no-cache-dir "dns-lexicon>=3.23.2" "ovh>=1.0.0"
```

**Comment by ohemorange** [comment]
That's expected, because the latest release of lexicon does not yet include the fix. As mentioned above, if you would like the fix to be available, comment on the linked lexicon PR.

**Comment by chikeb-aymen** [comment]
We ran into the same problem with OVH TXT records not being cleaned up when issuing multiple wildcards.
Our workaround: custom certbot/dns-ovh image with updated dns-lexicon plus an OVH API cleanup script run from a Kubernetes CronJob.
Code and example manifests: [https://github.com/<your-username>/certbot-ovh-dns-cleanup](https://github.com/chikeb-aymen/certbot-ovh-dns-cleanup)
One-file gist version: [https://gist.github.com/chikeb-aymen/a93e079497ca2964f0eedab60bfca04e](https://gist.github.com/chikeb-aymen/a93e079497ca2964f0eedab60bfca04e).

**Comment by HLFH** [comment]
Lexicon [v3.24.0](https://github.com/dns-lexicon/dns-lexicon/releases/tag/v3.24.0) has just been released. They also released v3.25.0 and v3.25.1, and they all have the fix.

**Comment by ohemorange** [comment]
nice, thanks for tracking! I'll pull it in now, should be in the next release, which is scheduled for a week from today

**Comment by ohemorange** [comment]
Released!
