### ISSUE TITLE
Running with 192MB RAM is not enough

### ISSUE THREAD

**Issue by nagisa** [certbot/certbot#1081]
`python-cryptography` apparently tries to compile a pretty big C binding or something like that, and gcc proceeds to ICE due to lack of free memory.

The `letsencrypt-auto` tool should know its memory requirements and ask whether you really want to proceed if you haven’t enough.

**Comment by DenisMir** [comment]
Got the same problem on a 512MB Digitalocean droplet. So no chance of testing it.

**Comment by centminmod** [comment]
this could be problematic.. anything can be done about it ? I think 512MB minimum VPS size would be a good target to aim for.

**Comment by spede** [comment]
Won't compile on a DO 512MB droplet even with `--param ggc-min-expand=0 --param ggc-min-heapsize=8192`. I think the only option for now is to wait for an operating system package.

**Comment by pde** [comment]
OS packages are already available for Debian experimental, Arch, and FreeBSD.  More should be on the way.

**Comment by pde** [comment]
But if you really need to work around this in the meantime, there are workarounds:

1. You could also probably just rsync the venv directory `~/.local/share/letsencrypt` from a machine with more RAM.

2 Try [making a swapfile](http://www.cyberciti.biz/faq/linux-add-a-swap-file-howto/) to give yourself more memory.  If your instance is spinning-disk-backed, this may be horribly slow, but SSD should be okay.

**Comment by nagisa** [comment]
> OS packages are already available for Debian experimental, Arch, and FreeBSD. More should be on the way.

The native package that’s giving trouble (python-cryptography) is already available on many distributions (notable exception being current LTS of Ubuntu), but of incompatible version (?).

> You could also probably just rsync the venv directory ~/.local/share/letsencrypt from a machine with more RAM.

That’s way to naive. letsencrypt builds native libraries and these must be properly cross-compiled to “just-work” after being copy-pasted.

--- 

That being said, it is pretty hard to make letsencrypt-auto to use already installed python packages. I had to do whole installation (into virtual environ) manually after installing all the dependencies from the OS.

Probably the first good step would be an option to use OS’s python packages that are available, only building and installing missing ones.

**Comment by spede** [comment]
Gave the Debian package a go, and it seems `python-letsencrypt` has got a problem with it. `python-letsencrypt : Dependencies: python-acme (= 0.0.0.dev20151114) but 0.0.0.dev20151114-1 is to be installed` - it's asking explicitly for `dev20151114` whereas the only package available is `dev20151114-1`.

**Comment by ArchimedesPi** [comment]
[Another full trace of the issue](http://ix.io/msn), provided by someone on IRC.

**Comment by centminmod** [comment]
still an issue ? i only tested on 1GB VPS.  minimum memory requirements ?

**Comment by huanga** [comment]
128M VPS on BuyVM crashing with the same problem. I only found out about this problem after searching for the error I was encountering. 128M is pitifully small, but it works great for tiny single web app that doesn't have a lot of traffic. I could upgrade to something larger, but that would be quite a waste. What is the target size LetsEncrypt is shooting to support?

**Comment by kuba** [comment]
@huanga, one think you could try is to build `simp_le` binary out of https://github.com/kuba/simp_le/tree/master/pyi and copy it over to your server - memory requirements should be minimal.

**Comment by centminmod** [comment]
another person hit https://community.letsencrypt.org/t/letsencrypt-auto-error-errno-12-cannot-allocate-memory/6359/

**Comment by alex** [comment]
We're working on a fix for this in cffi+cryptography. Will update as
there's progress.

On Tue, Dec 8, 2015 at 8:23 PM, George Liu (eva2000) <
notifications@github.com> wrote:

> another person hit
> https://community.letsencrypt.org/t/letsencrypt-auto-error-errno-12-cannot-allocate-memory/6359/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/letsencrypt/letsencrypt/issues/1081#issuecomment-163076690>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by centminmod** [comment]
@alex cheers thanks for the heads up :+1:

**Comment by coolaj86** [comment]
If you want something super lightweight and easy to install with few dependencies...

https://github.com/Daplie/node-letsencrypt-cli

```bash
# Install node.js
curl -L bit.ly/iojs-min | bash

# Install LetsEncrypt
npm install -g letsencrypt-cli

# get certs
letsencrypt certonly \
  --agree-tos --email john.doe@example.com \
  --standalone \
  --domains example.com,www.example.com \
  --server https://acme-staging.api.letsencrypt.org/directory \

# take a look
ls ~/letsencrypt/etc/live
```

We don't have all of the apache config and whatnot, but if you just want your certs quick and easy - especially on low-mem and low-power platforms (DO, RPi), it'll do.

**Comment by the7th** [comment]
One way I use to avoid this issue is by restarting my VM. worked with DigitalOcean 512MB.

**Comment by centminmod** [comment]
any movement on this ? @bmw @jsha @pde

**Comment by macdonjo** [comment]
@the7th restarting your droplet gave you enough memory?

**Comment by the7th** [comment]
@macdonjo Yeah. Somehow it does.

**Comment by megasnort** [comment]
I'm using a Digital Ocean 512Mb droplet to run three django apps through gunicorn/nginx. At first I did not get letsencrypt installed and got the error above. As soon as I shut the 3 apps down, installation went fine. Problem seems indeed to be memory related.

**Comment by planetjones** [comment]
Same issue - I am trying to use on a 128MB VM.  I can't increase swop past 64MB.  I think lets encrypt should be usable even on low end boxes (Cent OS 6 - so maybe I need to wait for native packages?)

**Comment by feederror** [comment]
I was able to install certs on OpenVz/Ramnode 128MB RAM / 64 MB VRAM container with Ubuntu 14.04 **32-bit**.

The 32bit is the key. I was **not** able to install on Ubuntu 14.04 **64-bit**.

**Comment by pepa65** [comment]
Hitting this on Ramnode OpenVZ 128MB with 64-bit Ubuntu 14.04
Wondering how best to proceed: wait, try a different approach?

**Comment by planetjones** [comment]
My issue was on ram node - thing is you can't increase the swap. I just switched to using a python client (acme client) and it is up and running ok on cent os 6

**Comment by pepa65** [comment]
Right, swap is fixed, can't be added even through a file.
Is there a howto somewhere on using the acme client?

**Comment by planetjones** [comment]
Think I used this wrapper - then you only need Python and OpenSSL 

https://github.com/diafygi/acme-tiny/blob/master/README.md

**Comment by The-Penultimate-Defenestrator** [comment]
Same issue. On a 512MB droplet. I have swap space enabled (I think) but I still have the issue.

**Comment by Greenjam94** [comment]
Same issue on a 512MB Ubuntu droplet. I did the restart and it was able to run. The only things running on my server is a apache server, MySQL and irssi for IRC chats.

**Comment by Akiracr** [comment]
I have a DO of 512mb and it had had the same problem, I could solve it by creation of a swapfile

**Comment by DDecoene** [comment]
I was able to get is going by stopping (`sudo service apache2 stop`) the apache service and then running `letsencrypt-auto` on my debian wheezy. It really was due to memory. Hope this helps someone.

**Comment by The-Penultimate-Defenestrator** [comment]
@DDecoene Worked for me.

**Comment by tifroz** [comment]
+1 would really like to see this fixed. Right now we have to manually stop all running servers every time we need to renew in order to make it work, which defeats the automation

**Comment by pepa65** [comment]
I upgraded to from OpenVZ 128M+64M to KVM 512M and no longer have this problem. It would be nice to have letsencrypt-auto work on low-memory though for the affected systems/distros.

**Comment by bmw** [comment]
@tifroz, this problem should only occur when installing or upgrading Certbot using `{certbot,letsencrypt}-auto`. If you're using one of the `auto` scripts, [we generally recommend](https://certbot.eff.org/#pip-other) to provide `--no-self-upgrade` on the command line which will prevent the script and Certbot from auto updating which both increases stability and avoids this problem.

**Comment by tifroz** [comment]
@bmw Thank you for the guidance. I can't seem to get the `--no-self-upgrade` to have any effect however. When executing `./certbot-auto renew --no-self-upgrade --quiet --dry-run --staging > "/var/log/apps/letsencrypt.log"`, I am getting this output (pruned for brevity):

```
Bootstrapping dependencies for Debian-based OSes...
Hit http://security.ubuntu.com trusty-security InRelease
...
Reading package lists...
...
The following extra packages will be installed:
  libssl1.0.0
The following packages will be upgraded:
  libssl-dev libssl1.0.0
2 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Need to get 1,904 kB of archives.
After this operation, 6,144 B of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by gabeluci** [comment]
I managed to solve this issue by renewing one cert at a time.

This bash script will use `certbot certificates` to find all the certificate names, then renew each one separately:

```
#!/bin/bash

for cert in `certbot certificates 2>/dev/null | grep "Certificate Name:" | cut -d: -f2-`
do
    certbot renew -q --cert-name $cert
done
```

I ran this on a cheap VPS with 128MB of RAM and 8 certificates. It worked without having to stop Apache.
