### ISSUE TITLE
letsencrypt-auto should save debug logs

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1320]
`letsencrypt-auto` by default should save all installation logs, somewhere; `/var/log/letsencrypt/letsencrypt.log` contains only logs from the `letsencrypt` binary itself, so debugging broken users is harder.

**Comment by devnsec-com** [comment]
Since `/var/log/letsencrypt` directory owned by `root`, and permission is `drwx------`, `letsencrypt-auto` will not be able to write to `/var/log/letsencrypt/letsencrypt.log`, perhaps, we can write logs to a temporary location, and delete it if the command successfully finished?

**Comment by SwartzCr** [comment]
I believe this is now resolved, @bmw?

**Comment by bmw** [comment]
`letsencrypt-auto` still doesn't do any of it's own logging. Like Jakub says in the original post, the only logs come from letsencrypt/Certbot itself and not the `*-auto` script.

**Comment by ohemorange** [comment]
We're redoing packaging. Whether or not the new way includes logs, I don't think this issue is a good place to track that. Thanks for bringing it up; I'll include it in the relevant place!
