### ISSUE TITLE
Document supported platforms

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#1975]
As far as I can tell on https://letsencrypt.readthedocs.org/en/latest/using.html, we don't document supported platforms. We should list them. In particular, I believe OS X isn't fully supported at the moment.

**Comment by pde** [comment]
We have that here:
https://github.com/letsencrypt/letsencrypt/#system-requirements
which also shows up at:
https://letsencrypt.readthedocs.org/en/latest/intro.html#system-requirements

**Comment by bmw** [comment]
@pde, @jsha: are you sure this issue is resolved?

We do document the supported platforms for the Apache plugin, but not for the client as a whole?

**Comment by jsha** [comment]
I agree this isn't resolved. That doc says "Unix-ish OSes," but OS X is Unix-ish and not supported. Could we specifically list the platforms that we test on or are known to work, at the top of that section?

**Comment by jsha** [comment]
Right now the docs say:

> The Apache plugin currently requires an OS with augeas version 1.0; currently it supports modern OSes based on Debian, Fedora, SUSE, Gentoo and Darwin.

But I think we support macOS now. Also, we should say here whether Windows is supported.

**Comment by sydneyli** [comment]
@jsha How about if in the documentation, we linked to the [instruction generators](https://certbot.eff.org/) on the front page? I think it's fairly thorough.

**Comment by jsha** [comment]
I don't think the instruction generators really answer the question as effectively. They just say "I'm using <software> on <system>." They don't say "you must be using one of these systems to use Certbot." It would be easy to imagine a system that Certbot works on, but that doesn't have instructions on the generator.

**Comment by jsha** [comment]
The documentation at https://github.com/certbot/certbot#system-requirements and https://letsencrypt.readthedocs.io/en/latest/intro.html#system-requirements is still wrong, but in a different way:

> This client runs on Unix-based operating systems.

Certbot now runs on Windows, too.

**Comment by adferrand** [comment]
Hello @jsha! Indeed, certbot is technically working on Windows. However, we didn't reach yet a production-grade quality so we need to wait a little more before updating the documentation and make this official.

But we are not far to that, and so this issue will be ready to be closed in few months :)
