### ISSUE TITLE
Failed to run Apache plugin non-interactively

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2600]
As described at 

https://community.letsencrypt.org/t/trouble-automatically-renewing-with-a-script/11894

a hand-written `default-ssl.conf` containing various VirtualHosts is giving 

```
Failed to run Apache plugin non-interactively
Missing command line flag or config entry for this setting:
We were unable to find a vhost with a ServerName or Address of subdomain.client1.com.
Which virtual host would you like to choose?
```

when running `letsencrypt renew`. This looks like a problem with the `apache` plugin to me.

**Comment by misterch0c** [comment]
+1

**Comment by bmw** [comment]
Looking at the post on the community forum, I believe this is a dupe of #2320. Multiple virtual hosts per file is not currently supported by the Apache plugin (see #1042), however, the plugin fails to recognize the problem.

**Comment by mgedmin** [comment]
I'm getting this problem when I have just two `<VirtualHost>` directives in the .conf file for a particular vhost (one for port *:80, one for port *:443, both with the same ServerName).

I'm pretty sure this used to work with older LetsEncrypt versions.

Can I ask the Apache authenticator plugin with a command-line option or something to please stop trying to verify that my Apache config is correct and just proceed with the TLS-SNI-01 challenge?

**Comment by mgedmin** [comment]
I've been reading the source code again, trying to understand why the Apache *authenticator* plugin needs to parse virtual host files when it doesn't need to modify them.

The call is in tls_sni_01.py, in _get_addrs(): the plugin wants to know what IP addresses are used for the domains you're verifying.

**Comment by pde** [comment]
Should have been fixed by #2906

**Comment by frozen-solid** [comment]
Still having a problem with this bug as of today, though I'm wondering if my issue might be related to having a hyphen in the domain name. I have 4 hosts all setup with exactly the same configs. The only difference is the directory, document root, and server names. However, the domain with a hyphen keeps throwing the error still.

**Comment by bmw** [comment]
@frozen-solid, how are you running the client? The fix in #2906 hasn't been packaged yet, so unless you're doing something like our [developer instructions](https://letsencrypt.readthedocs.io/en/latest/contributing.html), you won't have the fix yet. With that said, we're planning on doing a new client release, including that PR, later this week.

**Comment by frozen-solid** [comment]
Oh, well in that case you're right I wasn't using the dev instructions. I
wrongly assumed running from the git source would be enough. Thanks for the
information, and sorry for cluttering the issue report.
