### ISSUE TITLE
Dependency clash on Debian Jessie

### ISSUE THREAD

**Issue by ewjoachim** [certbot/certbot#3293]
When trying to install certbot for jessie-backports, I'm running into the following problem : 

``` bash
aptitude install python-certbot-apache -t jessie-backports
The following NEW packages will be installed:
  certbot{a} python-augeas{a} python-certbot{a} python-certbot-apache python-configargparse{a} python-configobj{a} python-dialog{a} 
  python-parsedatetime{a} python-psutil{a} python-pyicu{a} python-zope.component{a} python-zope.event{a} python-zope.interface{a} 
0 packages upgraded, 13 newly installed, 0 to remove and 54 not upgraded.
Need to get 806 kB of archives. After unpacking 4503 kB will be used.
The following packages have unmet dependencies:
 python-acme : Breaks: python-certbot (< 0.8.1) but 0.8.0-1~bpo8+2 is to be installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     certbot [Not Installed]                            
2)     python-certbot [Not Installed]                     
3)     python-certbot-apache [Not Installed] 

Accept this solution? [Y/n/q/?] n

*** No more solutions available ***

```

As far as I understand there seems to be a dependency clash. What should I do ?

**Comment by spieiga** [comment]
same issue here.  except my certbot was already installed, but I get a dependency issue when trying to apt-get upgrade

**Comment by pde** [comment]
@hlieberman I think this is for you :)

**Comment by Gholie** [comment]
Seems like I have the same issue, was installed and worked fine. Then I ran a apt-get dist-upgrade to install some updates, and during this update Certbot got removed.

> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  python-certbot-apache : Depends: certbot (>= 0.8.0~) but it is not going to be                                                                                         installed
>                          Depends: python-certbot but it is not going to be insta                                                                                        lled
> E: Unable to correct problems, you have held broken packages.

**Comment by hlieberman** [comment]
This is resolved.  FYI, @pde

**Comment by Hollerweger** [comment]
not resolved for me:
aptitude install python-certbot-apache -t jessie-backports
The following NEW packages will be installed:
  augeas-lenses{a} certbot{a} dialog{a} libaugeas0{a} python-acme{ab} python-augeas{a} python-certbot{ab} 
  python-certbot-apache python-configargparse{a} python-configobj{a} python-dialog{a} python-mock{a} 
  python-parsedatetime{a} python-pyicu{a} python-rfc3339{a} python-setuptools{a} python-tz{a} 
  python-zope.component{a} python-zope.event{a} python-zope.interface{a} 
The following partially installed packages will be configured:
  redmine 
0 packages upgraded, 20 newly installed, 0 to remove and 5 not upgraded.
Need to get 1,911 kB of archives. After unpacking 8,649 kB will be used.
The following packages have unmet dependencies:
 python-acme : Depends: python-openssl (>= 0.15) but 0.14-1 is installed.
               Depends: python-cryptography (>= 0.8) but 0.6.1-1 is installed.
               Depends: python-setuptools (>= 11.3~) but 5.5.1-1 is to be installed.
 python-certbot : Depends: python-cryptography (>= 0.7) but 0.6.1-1 is installed.
                  Depends: python-psutil (>= 2.2.1) but it is not going to be installed.
open: 2; closed: 1; defer: 0; conflict: 0                                                                       .The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     certbot [Not Installed]                            
2)     python-acme [Not Installed]                        
3)     python-certbot [Not Installed]                     
4)     python-certbot-apache [Not Installed]              

Accept this solution? [Y/n/q/?]

**Comment by vincelord** [comment]
I  got the same problem

**Comment by hlieberman** [comment]
If you're still having problems, make sure you've installed the packages using -t jessie-backports, a la:
`apt-get install -t jessie-backports certbot python-certbot-apache`.

**Comment by chris42** [comment]
I have the same problem. -t jessie-backports does not work.
For me I get version conflicts on sort of packages as described above. e.g. python-cryptography, python-setuptools, which all have to old versions.
