### ISSUE TITLE
opensuse Tumbleweed: Each time I run certbot, a line with `Listen 443` gets added to `/etc/apache2/httpd.conf`

### ISSUE THREAD

**Issue by jpluimers** [certbot/certbot#3364]
On openSUSE Tumbleweed, each time I run certbot, a line with `Listen 443` gets added to `/etc/apache2/httpd.conf`.

See this diff:

```
# git diff /etc/apache2/httpd.conf | more
diff --git a/apache2/httpd.conf b/apache2/httpd.conf
index eb9bd25..11e1962 100644
--- a/apache2/httpd.conf
+++ b/apache2/httpd.conf
@@ -229,4 +229,6 @@ IncludeOptional /etc/apache2/vhosts.d/*.conf
 <IfModule mod_ssl.c>
 Listen 443
 Listen 443
+Listen 443
+Listen 443
 </IfModule>
```

**Comment by pde** [comment]
@jpluimers can you check to see if this is still present in the latest git master? Instructions for running that are [here](https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client).

**Comment by pde** [comment]
Actually, discussing this with @joohoi, we believe this is probably fixed by #3356 (which isn't yet merged in master).

**Comment by joohoi** [comment]
@jpluimers could you test out the current master branch and report if it still is an issue?

**Comment by jpluimers** [comment]
Still fails:

```
# git diff apache2/httpd.conf | more
diff --git a/apache2/httpd.conf b/apache2/httpd.conf
index 7bbabd5..eb9bd25 100644
--- a/apache2/httpd.conf
+++ b/apache2/httpd.conf
@@ -228,4 +228,5 @@ IncludeOptional /etc/apache2/vhosts.d/*.conf
 #       easier :) 
 <IfModule mod_ssl.c>
 Listen 443
+Listen 443
 </IfModule>
```

This was after:

```
(venv) # git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
(venv) # certbot install --noninteractive --apache --cert-path /etc/letsencrypt/live/pcm.4delphi.com/fullchain.pem --fullchain-path /etc/letsencrypt/live/pcm.4delphi.com/fullchain.pem --key-path /etc/letsencrypt/live/pcm.4delphi.com/privkey.pem --domains pcm.4delphi.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
```

This is `/var/log/letsencrypt/letsencrypt.log`:

```
2016-08-13 17:49:42,202:DEBUG:certbot.main:Root logging level set at 20
2016-08-13 17:49:42,204:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-08-13 17:49:42,205:DEBUG:certbot.main:certbot version: 0.9.0.dev0
2016-08-13 17:49:42,205:DEBUG:certbot.main:Arguments: ['--noninteractive', '--apache', '--cert-path', '/etc/letsencrypt/live/pcm.4delphi.com/fullchain.pem', '--fullchain-path', '/etc/letsencrypt/live/pcm.4delphi.com/fullchain.pem', '--key-path', '/etc/letsencrypt/live/pcm.4delphi.com/privkey.pem', '--domains', 'pcm.4delphi.com']
2016-08-13 17:49:42,206:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-08-13 17:49:42,206:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2016-08-13 17:49:43,872:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7fd36bb95650>
Prep: True
2016-08-13 17:49:43,876:DEBUG:certbot.plugins.selection:Selected authenticator None and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7fd36bb95650>
2016-08-13 17:49:44,148:INFO:certbot_apache.configurator:Deploying Certificate to VirtualHost /etc/apache2/vhosts.d/pcm.4delphi.com-ssl.conf
2016-08-13 17:49:44,149:DEBUG:certbot_apache.configurator:Apache version is 2.4.23
2016-08-13 17:49:44,202:DEBUG:certbot.reverter:Creating backup of /etc/apache2/httpd.conf
2016-08-13 17:49:44,203:DEBUG:certbot.reverter:Creating backup of /etc/apache2/vhosts.d/pcm.4delphi.com-ssl.conf
```

**Comment by joohoi** [comment]
We discussed about this in the call, I have an idea how to proceed, but few bits of information would help (not actually related to the issue in question, but SuSE): 

Is there a clear way to obtain a list of activated modules from apache in SuSE? Centos for example lists the active modules with command "httpd -M".

**Comment by jpluimers** [comment]
Yes, `httpd -M` works op opensuse too, but the preferred way is `httpd2 -M` as it's about `apached2` (so for instance there is `/etc/apache2/` but not `/etc/apache/`.

On my system:

```
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 mpm_prefork_module (static)
 unixd_module (static)
 systemd_module (static)
 actions_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_file_module (shared)
 authz_host_module (shared)
 authz_groupfile_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cgi_module (shared)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 include_module (shared)
 log_config_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 setenvif_module (shared)
 ssl_module (shared)
 socache_shmcb_module (shared)
 userdir_module (shared)
 reqtimeout_module (shared)
 authn_core_module (shared)
 authz_core_module (shared)
 php7_module (shared)
 proxy_module (shared)
 proxy_http_module (shared)
 version_module (shared)
```

**Comment by jsoref** [comment]
http://benincampus.blogspot.ca/2015/10/show-complete-apache-config-file.html

**Comment by jpluimers** [comment]
@jsoref Thanks!

Since I could not find how to post comments there, and it works better for me having a repo, I put it into a gist with attribution to hist post: https://gist.github.com/jpluimers/fd300f3a500cbc78cd862d2a248e7b03
 
I need to adapt it for OpenSuSE; until then run it as this:

```
python CombineApacheConfig.py /etc/apache2/httpd.conf /tmp/apache2.combined.conf
```

**Comment by SwartzCr** [comment]
Should be fixed now that #4179 is merged, closing

**Comment by jpluimers** [comment]
It's back since 1.18.1 when running on OpenSuSE Tumbleweed, but mabye in a different form.

Let me know if I should file a new issue, or re-open this one.

Basically it comes down to `certbot-auto` not parsing the full Apache configuration as mentioned by @jsoref [earlier this year](https://github.com/certbot/certbot/issues/3364#issuecomment-271783828).

This is the `etckeeper` diff:

```
diff --git a/apache2/httpd.conf b/apache2/httpd.conf
index 7d2750f..a0f2184 100644
--- a/apache2/httpd.conf
+++ b/apache2/httpd.conf
@@ -230,3 +230,6 @@ IncludeOptional /etc/apache2/vhosts.d/*.conf
 #<IfModule mod_ssl.c>
 #Listen 443
 #</IfModule>
+<IfModule mod_ssl.c>
+Listen 443
+</IfModule>
diff --git a/apache2/vhosts.d/www.pluimers.com-ssl.conf b/apache2/vhosts.d/www.pluimers.com-ssl.conf
index 4cef95c..75c60f0 100644
--- a/apache2/vhosts.d/www.pluimers.com-ssl.conf
+++ b/apache2/vhosts.d/www.pluimers.com-ssl.conf
@@ -45,8 +45,8 @@
        SSLEngine on
 
        #   You can use per vhost certificates if SNI is supported.
-       SSLCertificateFile /etc/letsencrypt/live/pluimers.com/fullchain.pem
-       SSLCertificateKeyFile /etc/letsencrypt/live/pluimers.com/privkey.pem
+       SSLCertificateFile /etc/letsencrypt/live/ans.pluimers.com/fullchain.pem
+       SSLCertificateKeyFile /etc/letsencrypt/live/ans.pluimers.com/privkey.pem
 
        #   Per-Server Logging:
        #   The home of a custom SSL log file. Use this when you want a
```

The problem is that OpenSuSE ships with this `/etc/apache2/listen.conf`:

```
# Listen: Allows you to bind Apache to specific IP addresses and/or
# ports. See also the <VirtualHost> directive.
#
# http://httpd.apache.org/docs/2.4/mod/mpm_common.html#listen
#
# Change this to Listen on specific IP addresses as shown below to 
# prevent Apache from glomming onto all bound IP addresses (0.0.0.0)
#
# When we also provide SSL we have to listen to the 
# standard HTTP port (see above) and to the HTTPS port
#
# Note: Configurations that use IPv6 but not IPv4-mapped addresses need two
#       Listen directives: "Listen [::]:443" and "Listen 0.0.0.0:443"
#
#Listen 12.34.56.78:80
#Listen 80
#Listen 443

Listen 80


<IfDefine SSL>
        <IfDefine !NOSSL>
        <IfModule mod_ssl.c>

                Listen 443

        </IfModule>
        </IfDefine>
</IfDefine>


# Use name-based virtual hosting
# 
# - on a specified address / port:
#
#NameVirtualHost 12.34.56.78:80
#
# - name-based virtual hosting:
#
#NameVirtualHost *:80
#
# - on all addresses and ports. This is your best bet when you are on
#   dynamically assigned IP addresses:
#
#NameVirtualHost *
```

**Comment by joohoi** [comment]
Reopening the issue. I'm working on parsing the apache defines correctly from the static file on OpenSUSE, so this will get fixed in the future. Certbot is currently unavailable to find those, because OpenSUSE adds them in an rather exotic way.

**Comment by jpluimers** [comment]
@joohoi I know and I have enough spare Raspberry Pi machines or VMs to try this out on. Just let me know when you need help.

**Comment by jpluimers** [comment]
@joohoi any progress on this? Or a temporary option to skip modifying the `Listen` entry at all?

The entry is now added for each renewal during `certbot-auto renew`.

To work around this, I have to retry the `certbot-auto renew` in a loop combined with restoring `/etc/apache2/httpd.conf` and restarting httpd2 until there is no "red" in the output any more

That in turn leads to failures like this:

```
Attempting to renew cert (subdomain.domain.tld) from /etc/letsencrypt/renewal/subdomain.domain.tld.conf produced an unexpected error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new authz :: Too many failed authorizations recently.. Skipping.
```

Which is "red", which is a sort of Catch-22 situation (:

**Comment by joohoi** [comment]
Yes! There's progress. I suspect this issue will be fixed by #5202 . Feel free to test it out if it works for you, but be noted that this is still a work in progress, and the PR hasn't been completely reviewed yet.

The issue for OpenSUSE was that we weren't able to read the complete Apache configuration because the init scripts add generated include files directly on the Apache command line instead of referencing them from the root `httpd.conf`. This makes the current Certbot behavior (passive configuration file parsing) to not see all of the config. #5202 parses output of httpd binary listing active includes and adds them to Augeas DOM if needed. That should make Certbot "see" the complete configuration tree.

**Comment by jpluimers** [comment]
@joohoi Thanks! 

I forgot where the test-docs are to test a specific branch. Any pointers to that?

I know the underlying reason why it parsed wrongly as that has been mentioned before in [1](https://github.com/certbot/certbot/issues/3364#issuecomment-271783828) and [2](https://github.com/certbot/certbot/issues/3364#issuecomment-271869742), so I'm glad you found a way to fix it.

I just re-tested the 0.19 behaviour and it indeed is the below diff which seems to make it different from https://github.com/certbot/certbot/issues/3967

```
[root@revue:/etc] # git diff /etc/apache2/httpd.conf | more
diff --git a/apache2/httpd.conf b/apache2/httpd.conf
index 7d2750f..a0f2184 100644
--- a/apache2/httpd.conf
+++ b/apache2/httpd.conf
@@ -230,3 +230,6 @@ IncludeOptional /etc/apache2/vhosts.d/*.conf
 #<IfModule mod_ssl.c>
 #Listen 443
 #</IfModule>
+<IfModule mod_ssl.c>
+Listen 443
+</IfModule>
```

**Comment by joohoi** [comment]
Yeah, to run a local copy of Certbot, pull the repo, checkout the branch, and follow: https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client

**Comment by jpluimers** [comment]
It seems that the last try managed to renew the remaining domain, so I will need to either wait a while or find a way to force renew a domain that has not yet expired. Any tips?

**Comment by joohoi** [comment]
There is `--force-renewal` cli parameter for this. It will however affect all the domains.

**Comment by jpluimers** [comment]
Thanks, below is what I was doing (so I can find back what I did) and where it fails. 

It's based on:

- https://github.com/certbot/certbot/pull/5202 (which does not link to the `alt_override` tree, shame on GitHub)
- https://github.com/certbot/certbot/tree/alt_override
- https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client
- https://github.com/certbot/certbot/issues/3364#issuecomment-271783828
- https://gist.github.com/jpluimers/fd300f3a500cbc78cd862d2a248e7b03

```
# cd ~/Versioned/certbot
# git fetch --all
Fetching origin
# git checkout alt_override
Branch 'alt_override' set up to track remote branch 'alt_override' from 'origin'.
Switched to a new branch 'alt_override'
# ./certbot-auto --os-packages-only
OS packages installed.
# ./tools/venv.sh
... very long log ...
Please run the following command to activate developer environment:
source venv/bin/activate
# source ./venv/bin/activate
[venv] # ./certbot-auto renew --force-renewal
...
-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/4delphi.com.conf
-------------------------------------------------------------------------------
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for 4delphi.com
tls-sni-01 challenge for www.4delphi.com
Error while running apache2ctl configtest.

AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
AH00526: Syntax error on line 234 of /etc/apache2/httpd.conf:
Cannot define multiple Listeners on the same IP:port

Cleaning up challenges
Error while running apache2ctl configtest.

AH00526: Syntax error on line 234 of /etc/apache2/httpd.conf:
Cannot define multiple Listeners on the same IP:port

Encountered exception during recovery
Error while running apache2ctl configtest.

AH00526: Syntax error on line 234 of /etc/apache2/httpd.conf:
Cannot define multiple Listeners on the same IP:port
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1945, in cleanup
    self.restart()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1833, in restart
    self.config_test()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1856, in config_test
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl configtest.

AH00526: Syntax error on line 234 of /etc/apache2/httpd.conf:
Cannot define multiple Listeners on the same IP:port

Attempting to renew cert (4delphi.com) from /etc/letsencrypt/renewal/4delphi.com.conf produced an unexpected error: Error while running apache2ctl configtest.

AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
AH00526: Syntax error on line 234 of /etc/apache2/httpd.conf:
Cannot define multiple Listeners on the same IP:port
. Skipping.
...
```

The problem: there is no line `234` in that file:

```
[venv] # wc -l /etc/apache2/httpd.conf
232 /etc/apache2/httpd.conf
```
There is a Listen in comments there though:

```
[venv] # tail /etc/apache2/httpd.conf

# Note: instead of adding your own configuration here, consider 
#       adding it in your own file (/etc/apache2/httpd.conf.local)
#       putting its name into APACHE_CONF_INCLUDE_FILES in 
#       /etc/sysconfig/apache2 -- this will make system updates 
#       easier :) 
## if letsencrypt adds Listen 443 again, then manually remove it as it clashes with listen.conf
#<IfModule mod_ssl.c>
#Listen 443
#</IfModule>
```
So I combined the apache configs like [explained before](https://github.com/certbot/certbot/issues/3364#issuecomment-271783828) using my [`CombineApacheConfig`  gist](https://gist.github.com/jpluimers/fd300f3a500cbc78cd862d2a248e7b03) :

```
[venv] # python ../CombineApacheConfig/CombineApacheConfig.py /etc/apache2/httpd.conf /tmp/apache2.combined.conf
[2017-11-22 13:59:38,330][INFO]:Done writing /tmp/apache2.combined.conf
[venv] # grep Listen /tmp/apache2.combined.conf 
Listen 80
		Listen 443
[venv] # grep -r --exclude="*~" Listen /etc/apache2/
/etc/apache2/listen.conf:# Listen: Allows you to bind Apache to specific IP addresses and/or
/etc/apache2/listen.conf:# Change this to Listen on specific IP addresses as shown below to 
/etc/apache2/listen.conf:#       Listen directives: "Listen [::]:443" and "Listen 0.0.0.0:443"
/etc/apache2/listen.conf:#Listen 12.34.56.78:80
/etc/apache2/listen.conf:#Listen 80
/etc/apache2/listen.conf:#Listen 443
/etc/apache2/listen.conf:Listen 80
/etc/apache2/listen.conf:		Listen 443
/etc/apache2/httpd.conf:## if letsencrypt adds Listen 443 again, then manually remove it as it clashes with listen.conf
/etc/apache2/httpd.conf:#Listen 443
```

It looks like the new certbot config combining differs from combining it in a simple Python script. 

Is there any way to have https://github.com/certbot/certbot/pull/5202 dump the combined configuration somewhere?

**Comment by jsoref** [comment]
In the past, I've hacked certbot to do that. You can definitely find the place where it writes out/renames/deletes the file and have it make a copy (or rename/move instead of deleting).

I've personally asked for this feature to be available for normal end user debugging (it's frustrating w/ my admin hat).

**Comment by joohoi** [comment]
@jpluimers there's no easy way to dump the configuration in cases where it fails sanity checks. To see the configuration state at the point of doing validation, we have an option already in the client: `--debug-challenges` which will pause the execution before asking LE to do the challenge validation.

Back to the original issue; unfortunately you still weren't running the local copy of the client, the correct way of running local copy after `source venv/bin/activate` would be `sudo venv/bin/certbot` instead of `./certbot-auto`. I still believe the configuration visibility added by #5202 will fix this exact issue.

**Comment by jpluimers** [comment]
@joohoi More information because of:

- the stack trace
- https://github.com/certbot/certbot/pull/5202/files#diff-bdd584c1dc4f4d6316df485617bec545L1854 calling `util.run_script(constants.os_constant("conftest_cmd"))`
- https://github.com/certbot/certbot/pull/5202/files#diff-aae4e9d3f51b4631437ebf674e3a1791R12 containing for `conftest_cmd=['apache2ctl', 'configtest'],`
- https://github.com/certbot/certbot/blob/9ba9b36126768012fd225e6d0f05e55475db20bd/certbot/util.py#L64 indicating `run_script` is a small wrapper around `subprocess.Popen`
- https://serverfault.com/questions/66363/environment-variables-of-a-running-process-on-unix

```
# apache2ctl configtest
AH00558: httpd-prefork: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
Syntax OK
[venv] # cat /var/run/httpd.pid
2969
[venv] # ps -ax | grep `cat /var/run/httpd.pid`
 2969 ?        Ss     0:00 /usr/sbin/httpd-prefork -DSYSCONFIG -DSSL -C PidFile /var/run/httpd.pid -C Include /etc/apache2/sysconfig.d//loadmodule.conf -C Include /etc/apache2/sysconfig.d//global.conf -f /etc/apache2/httpd.conf -c Include /etc/apache2/sysconfig.d//include.conf -DSYSTEMD -DFOREGROUND -k start
10916 pts/0    S+     0:00 grep --color=auto 2969
# xargs --null --max-args=1 echo < /proc/`cat /var/run/httpd.pid`/environ
APACHE_SERVER_FLAGS=SSL
APACHE_CONF_INCLUDE_FILES=
HTTPD_MODULE_PATHS= /usr/lib64/apache2-prefork/mod_actions.so /usr/lib64/apache2-prefork/mod_alias.so /usr/lib64/apache2-prefork/mod_auth_basic.so /usr/lib64/apache2-prefork/mod_authn_file.so /usr/lib64/apache2-prefork/mod_authz_host.so /usr/lib64/apache2-prefork/mod_authz_groupfile.so /usr/lib64/apache2-prefork/mod_authz_core.so /usr/lib64/apache2-prefork/mod_authz_user.so /usr/lib64/apache2-prefork/mod_autoindex.so /usr/lib64/apache2-prefork/mod_cgi.so /usr/lib64/apache2-prefork/mod_dir.so /usr/lib64/apache2-prefork/mod_env.so /usr/lib64/apache2-prefork/mod_expires.so /usr/lib64/apache2-prefork/mod_include.so /usr/lib64/apache2-prefork/mod_log_config.so /usr/lib64/apache2-prefork/mod_mime.so /usr/lib64/apache2-prefork/mod_negotiation.so /usr/lib64/apache2-prefork/mod_setenvif.so /usr/lib64/apache2-prefork/mod_ssl.so /usr/lib64/apache2-prefork/mod_socache_shmcb.so /usr/lib64/apache2-prefork/mod_userdir.so /usr/lib64/apache2-prefork/mod_reqtimeout.so /usr/lib64/apache2-prefork/mod_authn_core.so /usr/lib64/apache2-prefork/mod_proxy.so /usr/lib64/apache2-prefork/mod_proxy_http.so /usr/lib64/apache2-prefork/mod_proxy_connect.so /usr/lib64/apache2-prefork/mod_rewrite.so /usr/lib64/apache2-prefork/mod_version.so /usr/lib64/apache2/mod_php7.so
INVOCATION_ID=f8f6cbff5fa04ee8a8ead50487b79c9b
HTTPD_MODULE_IDS= actions_module alias_module auth_basic_module authn_file_module authz_host_module authz_groupfile_module authz_core_module authz_user_module autoindex_module cgi_module dir_module env_module expires_module include_module log_config_module mime_module negotiation_module setenvif_module ssl_module socache_shmcb_module userdir_module reqtimeout_module authn_core_module proxy_module proxy_http_module proxy_connect_module rewrite_module version_module php7_module
HTTPD_MPM=prefork
APACHE_SERVERADMIN=
NOTIFY_SOCKET=/run/systemd/notify
APACHE_ACCESS_LOG=/var/log/apache2/access_log combined
APACHE_USE_CANONICAL_NAME=off
SYSCONFIG_FILE=/etc/sysconfig/apache2
APACHE_SERVERTOKENS=ProductOnly
APACHE_LOGLEVEL=debug
APACHE_SERVERNAME=
PWD=/
LC_CTYPE=en_US.UTF-8
JOURNAL_STREAM=9:26808
APACHE_HTTPD_CONF=
APACHE_EXTENDED_STATUS=off
APACHE_SERVERSIGNATURE=off
APACHE_MPM=
APACHE_CONF_INCLUDE_DIRS=
APACHE_START_TIMEOUT=2
SHLVL=0
APACHE_MODULES=actions alias auth_basic authn_file authz_host authz_groupfile authz_core authz_user autoindex cgi dir env expires include log_config mime negotiation setenvif ssl socache_shmcb userdir reqtimeout authn_core mod_proxy mod_proxy_http mod_proxy_connect rewrite  version  php7
sysconfig_loaded=true
mpm_found=true
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
Browsing the certbot log file, I see this however:

```
2017-11-22 15:01:02,735:DEBUG:certbot.reverter:Creating backup of /etc/apache2/httpd.conf
2017-11-22 15:01:02,940:DEBUG:certbot_apache.parser:Adding Include /etc/apache2/vhosts.d/le_tls_sni_01_cert_challenge.conf to /files/etc/apache2/httpd.conf
2017-11-22 15:01:02,941:DEBUG:certbot_apache.tls_sni_01:writing a config file with text:
 <IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName 9aeef711101e5061b3336ccc2f3d6a54.c8c5860b756c4f1b4a0635b2849bc478.acme.invalid
    UseCanonicalName on
    SSLStrictSNIVHostCheck on

    LimitRequestBody 1048576

    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /var/lib/letsencrypt/GStYIlRYbaRkq-mU7TERj7HElBrECy4ZLUxsZRj63rA.crt
    SSLCertificateKeyFile /var/lib/letsencrypt/GStYIlRYbaRkq-mU7TERj7HElBrECy4ZLUxsZRj63rA.pem

    DocumentRoot /var/lib/letsencrypt/tls_sni_01_page/
</VirtualHost>

</IfModule>

2017-11-22 15:01:02,958:DEBUG:certbot.reverter:Creating backup of /etc/apache2/httpd.conf
2017-11-22 15:01:03,034:ERROR:certbot.util:Error while running apache2ctl configtest.

AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
AH00526: Syntax error on line 234 of /etc/apache2/httpd.conf:
Cannot define multiple Listeners on the same IP:port
```
A few things that confuse me:

1. **two** log entries `DEBUG:certbot.reverter:Creating backup of /etc/apache2/httpd.conf`, but no mentioning of a revert.
2. I cannot find `/etc/apache2/vhosts.d/le_tls_sni_01_cert_challenge.conf`
3. `certbot_apache.tls_sni_01` writes a config after the include

I tried to add more logging in `certbot/reverter.py`, but those do not appear in `/var/log/letsencrypt/letsencrypt.log`, not even if I remove all `certbot/*.pyc` files before running.

I made these changes:

```
--- a/certbot/reverter.py
+++ b/certbot/reverter.py
@@ -231,7 +231,7 @@ class Reverter(object):
             if filename not in existing_filepaths:
                 # Tag files with index so multiple files can
                 # have the same filename
-                logger.debug("Creating backup of %s", filename)
+                logger.debug("XCreating backup of %s", filename)
                 try:
                     shutil.copy2(filename, os.path.join(
                         cp_dir, os.path.basename(filename) + "_" + str(idx)))
@@ -287,6 +287,7 @@ class Reverter(object):
                 with open(os.path.join(cp_dir, "FILEPATHS")) as paths_fd:
                     filepaths = paths_fd.read().splitlines()
                     for idx, path in enumerate(filepaths):
+                        logger.debug("Restoring backup from %s", path)
                         shutil.copy2(os.path.join(
                             cp_dir,
                             os.path.basename(path) + "_" + str(idx)), path)
```

However, this change does get through in the log file:

```
--- a/certbot/util.py
+++ b/certbot/util.py
@@ -69,6 +69,8 @@ def run_script(params, log=logger.error):
 
     """
     try:
+        msg = "Running %s" % (" ".join(params))
+        log(msg)
         proc = subprocess.Popen(params,
                                 stdout=subprocess.PIPE,
                                 stderr=subprocess.PIPE,
```

**Comment by jpluimers** [comment]
Thanks, that nailed it: it now works. 

The steps below based on:

- https://github.com/certbot/certbot/pull/5202 (which does not link to the `alt_override` tree, shame on GitHub)
- https://github.com/certbot/certbot/tree/alt_override
- https://certbot.eff.org/docs/contributing.html#running-a-local-copy-of-the-client
- https://github.com/certbot/certbot/issues/3364#issuecomment-271783828
- https://github.com/certbot/certbot/issues/3364#issuecomment-346378228
- https://gist.github.com/jpluimers/fd300f3a500cbc78cd862d2a248e7b03

```
# cd ~/Versioned/certbot
# git fetch --all
Fetching origin
# git checkout alt_override
Branch 'alt_override' set up to track remote branch 'alt_override' from 'origin'.
Switched to a new branch 'alt_override'
# ./certbot-auto --os-packages-only
OS packages installed.
# ./tools/venv.sh
... very long log ...
Please run the following command to activate developer environment:
source venv/bin/activate
# source ./venv/bin/activate
[venv] # venv/bin/certbot renew --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log
...
-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/pluimers.com.conf
-------------------------------------------------------------------------------
Running apache2ctl configtest
Running apache2ctl -v
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for pluimers.com
tls-sni-01 challenge for www.pluimers.com
Running apache2ctl configtest
Running apache2ctl graceful
Waiting for verification...
Cleaning up challenges
Running apache2ctl configtest
Running apache2ctl graceful
Running apache2ctl configtest
Running apache2ctl graceful

-------------------------------------------------------------------------------
new certificate deployed with reload of apache server; fullchain is
/etc/letsencrypt/live/pluimers.com/fullchain.pem
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------

Congratulations, all renewals succeeded. The following certs have been renewed:
...
  /etc/letsencrypt/live/pluimers.com/fullchain.pem (success)
...
-------------------------------------------------------------------------------
```

Now I also see my extra logging (like the extra `Running apache2ctl` lines and what changed in `/var/log/letsencrypt/letsencrypt.log`).

I've subscribed to https://github.com/certbot/certbot/pull/5202 and will re-test https://github.com/certbot/certbot/tree/master shortly after it has been merged.

**Comment by joohoi** [comment]
I'll close the issue. Feel free to re-test the master branch, or 0.20 release @jpluimers and please let me know if you run into any problems!

This was fixed in #5202 by giving Certbot visibility over loaded modules in OpenSUSE.

**Comment by jpluimers** [comment]
Splendid:

```
# ./certbot-auto --help
Upgrading certbot-auto 0.19.0 to 0.20.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
...
# ./certbot-auto renew --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log
...
Congratulations, all renewals succeeded. The following certs have been renewed:
...
```
