### ISSUE TITLE
Nginx parser has trouble with existing TLS listener on 8443

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#3542]
I'm not sure what the underlying problem is, but `certbot-compatibility-test -ai` doesn't like this sample configuration file from our corpus (which has an existing HTTPS listener on port 8443, and an HTTP listener on port 80 that generates a redirect to the HTTPS site).

```
upstream django_server_random6822.example.org {
    server unix:/srv/http/random7047/live/website.sock;
}

server {
    listen 8443;
    server_name random6822.example.org;

    ssl on;
    ssl_certificate       /etc/nginx/empty_cert.pem;
    ssl_certificate_key   /etc/nginx/key2.pem;

    location /media/ {
        alias /srv/http/random7047/live/dynamic/public/;
        expires 7d;
    }
    location /static/ {
        alias /srv/http/random7047/live/static_collected/;
        expires 7d;
    }

    location / {
        proxy_pass http://django_server_random6822.example.org;
        include          /etc/nginx/proxy_params;
    }

    access_log /var/log/access.log combined;
    error_log  /var/log/error.log;
}

server {
    listen 80;
    server_name random6822.example.org;

    rewrite ^/(.*) https://random6822.example.org:8443/$1;
}
```

**Comment by bmw** [comment]
We fail both authentication and installation. During authentication, we set up a temporary server block for the purposes of solving the `tls-sni` challenge. We create this server block listening on the same addresses and ports as the matching server block for the requested domain name. In this case, the vhost isn't listening on port 443 so it fails authentication.

Installation is similar. With our current logic, we install the cert into the existing SSL vhost. In this exaple, the vhost isn't listening on port 443 so when we attempt to connect to validate the cert, we fail to do so.

**Comment by ohemorange** [comment]
We can probably address this in #3549 - it might even make most sense to do as we do now, because if it's set up this way in the wild there might be some other proxy or redirect stuff going on, and we'll successfully end up connecting to that port. But it's probably ok to fail on non-443 ports for now.

**Comment by grantwwu** [comment]
https://community.letsencrypt.org/t/cert-renewal-failure-but-dns-appears-to-be-fine/49213

I may have run into this issue in the above thread - do y'all think it's the same situation?

**Comment by adferrand** [comment]
This issue has not been updated for a long time. So I assume it is solved, or not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.

**Comment by grantwwu** [comment]
@schoen as the original reporter of this issue, is certbot still failing that test?
