### ISSUE TITLE
apt-get Installation failure

### ISSUE THREAD

**Issue by batkins62** [certbot/certbot#4550]
## My operating system is (include version):
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
root@pleiades:/opt# apt-get install python-certbot
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-certbot : Depends: python-dialog (>= 3.2.2rc1) but it is not going to be installed
                  Depends: python-zope.component but it is not installable
                  Recommends: certbot but it is not going to be installed
                  Recommends: python-psutil (>= 2.2.1) but it is not going to be installed

**Comment by BartEmbregts** [comment]
apt-get install software-properties-common
add-apt-repository ppa:certbot/certbot
apt-get update
apt-get install certbot

done

**Comment by SwartzCr** [comment]
That's right!
As @BartEmbregts says, we're currently recommending that people install certbot from a ppa on ubuntu systems, since we were having trouble keeping the most up to date version in the official Ubuntu package repositories.
You can find those same instructions on certbot.eff.org
I'm going to close this ticket, as that should fix this problem for you - but feel free to re-open, or open another issue if you run into more problems!

**Comment by batkins62** [comment]
Thank you guys! still having problems:

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 certbot : Depends: python-certbot (= 0.11.1-1+certbot~xenial+3) but it is
not going to be installed
E: Unable to correct problems, you have held broken packages.


any help is greatly appreciated!

**Comment by SwartzCr** [comment]
can you `sudo apt-get install -f` and see what happens?

**Comment by bogointeractive** [comment]
I am having the same issues on Debian 8 Min Install. It is still having the error coming up with missing the files. I have done it another way as well and still same issues. So not sure what is going on but any help getting this fixed would be great.

[https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-debian-8](url) is what I was using to secure my server.

**Comment by bogointeractive** [comment]
[]http://www.tecmint.com/secure-nginx-with-lets-encrypt-ssl-certificate-on-ubuntu-and-debian/(url) I found this site, not sure if it is a good work around for what you need but I am thinking it will work just the same. I am going to give it a try here and see if it works for me.

**Comment by batkins62** [comment]
root@pleiades:/opt# apt-get install -f
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Doesnt show i have any broken files at all, its extremely weird

**Comment by SwartzCr** [comment]
@bogointeractive @batkins62 if either of you would have time to log into IRC today at #letsencrypt on irc.freenode.net I'd be happy to do some hands on debugging! Just ping me, my screen name is swartzcr.
Otherwise I'll try to reproduce on a debian server at some point today

**Comment by SwartzCr** [comment]
According to @bogointeractive on IRC and Harlan, this is fixed now - closing. @batkins62 you should be able to install this now, as the version that is packaged has been fixed.
Feel free to open another ticket if you have new issues, or email me directly if this isn't fixed for you.
Sorry about the trouble!

**Comment by batkins62** [comment]
thanks again for the help! to summarize this resolution, the universe repo was not active, and a dependency was not going to be installed because of it. Ran: sudo add-apt-repository universe
