### ISSUE TITLE
Ignoring Provides line with DepCompareOp for package python-cffi-backend…

### ISSUE THREAD

**Issue by kierun** [certbot/certbot#5063]
## My operating system is (include version):

`Linux ook 4.9.36-x86_64-linode85 #1 SMP Thu Jul 6 15:31:23 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Via then official Ubuntu PPA.

## I ran this command and it produced this output:

N.A.

## What the problem is…

When running `apt-get update`, I get the following warning:
```

W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-max                                                                            
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-min                                                                            
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-max                                                                           
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-min                                                                                                                                                   
W: You may want to run apt-get update to correct these problems
```

Running `pat-get update` again does nothing whatsoever.  It appears that `
python-cffi-backend` is a dependency of certbot.  However, it breaks apt on 14.04.

*Is there any solutions for this?*

**Comment by kierun** [comment]
More information about what lead to this in the "[apt-get update warning: Ignoring Provides line with DepCompareOp for package…](https://askubuntu.com/q/946402/24976)" question on stack.

**Comment by SwartzCr** [comment]
I wouldn't say that this breaks apt. As is mentioned in that stack overflow comment - this warning is harmless. Is certbot not working for you? Are you unable to install other packages?
The W here means warning, so I wouldn't be to concerned about it, unless something else is going wrong as well.

**Comment by kierun** [comment]
Warnings are never harmless. They hint at a serious problem with the application. They should be fixed and not ignored.

That said, I removed the `certbot` PPA, removed all the packages it installed, and ran `apt` again. I even removed the `python-cffi-backend` package. However, the problem persists. I re-installed `certbot` and it is working as far as I can tell. There is no trace of `python-cffi-backend` on the system yet the dammed warning is still there. ☹

*If* `python-cffi-backend` is not in the list of dependencies for certbot, feel free to close this.

**Comment by PABourdin** [comment]
I can confirm the problem with simply wrong packaging of these packages:
```
python-cffi-backend-api-max
python-cffi-backend-api-min
python3-cffi-backend-api-max
python3-cffi-backend-api-min
python-cffi-backend-api-max
python-cffi-backend-api-min
python3-cffi-backend-api-max
python3-cffi-backend-api-min
```

One should notify the people responsible for the packaging of those, they need to remove the "versioned provides" from their packages for Trusty. It of course "only" generates a warning, but if fact, other applications might interpret apt warnings as errors and might stop working, like e.g. `aptitude` stopped working(!!!) for me.

Thanks and best greetings.

**Comment by kierun** [comment]
@PABourdin ☺ Thanks for confirming. Any idea who those people are?

**Comment by PABourdin** [comment]
@kierun No, sorry, I would have written it, if I knew, but one can search that on the web...

Other projects experience the same problem:
https://github.com/TheTorProject/ooni-probe/issues/460

**Comment by SwartzCr** [comment]
I've emailed the PPA maintainer to see if he can fix it in his PPA since he provides python-cffi, but I am still waiting for a response

**Comment by ccharlot** [comment]
Any news on what's happening ?
I installed certbod with the PPA no Ubuntu 14.04 and also have these messages..

**Comment by campones** [comment]
same.. :)  certbot is working fine though

**Comment by kierun** [comment]
The PPA maintainer(s) are the people to ask. Unless they solve it, there is not much chance of this ever being resolved.

**Comment by hackel** [comment]
For Ubuntu 14.04, python-cffi-backend (and python3-cffi-backend) both come from the official Certbot PPA:
http://ppa.launchpad.net/certbot/certbot/ubuntu/
It appears that they were backported from Debian, as the maintainer is listed as "Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>" which isn't strictly true.  It would be nice if we could get this patched in the Certbot PPA even if upstream hasn't "fixed" it yet. (I'm not sure this is actually a problem upstream.)

**Comment by bmw** [comment]
@oerdnj, are you able to help resolve this problem?

**Comment by mohammadmojrian** [comment]
@SwartzCr have you got your email answer ?

**Comment by passion8** [comment]
any update ?

**Comment by adrianmihalko** [comment]
same problem here

**Comment by leogaggl** [comment]
Same problem on multiple VPS.

**Comment by kierun** [comment]
PSA: Please note that there is a nice little button you can press to get a "+1" (aka thumb up) on the original post. It's on the top right of the message box and has a plus sign and a smiling face. **There is no need to post "me too".** We know it is a problem.

**Comment by PABourdin** [comment]
@kierun given the fact that the solution to the problem seems rather simple, but no action seems to be taken to solve the problem, I must say the situation is rather frustrating for "me too", which I can not express with a laughing smilie.

**Comment by oerdnj** [comment]
*rather simple*, wow, thanks for the assessment.

Nevertheless, it has been fixed now. Feel free to close the issue.

**Comment by PABourdin** [comment]
@oerdnj Cornfirmed, the invalid header line is nomore present in trusty packages.

This issue may be closed.

**Comment by kierun** [comment]
@oerdnj I am afraid this is not fixed for all packages:

```
; date                                                                         
Mon Oct 23 14:02:04 BST 2017 
; sudo apt-get update
[…]
Reading package lists... Done                                                  
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-max                                                                            
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-min                                                                            
W: You may want to run apt-get update to correct these problems          
```   

Only the Python 3 ones have been fixed.

**Comment by oerdnj** [comment]
`apt-cache policy python-cffi-backend`
`apt-cache show python-cffi-backend`
?

**Comment by kierun** [comment]
@oerdnj Ah, my bad! Ubuntu does needs to `upgrade` as well as `update`… 

But here is the output in case that helps someone else.

```
; apt-cache policy python-cffi-backend  
python-cffi-backend:                    
  Installed: 1.10.0-0.1+ubuntu14.04.1+certbot+1                                 
  Candidate: 1.10.0-0.1+ubuntu14.04.1+certbot+1                                 
  Version table:    
 *** 1.10.0-0.1+ubuntu14.04.1+certbot+1 0                                       
        500 http://ppa.launchpad.net/certbot/certbot/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status                
; apt-cache show python-cffi-backend    
Package: python-cffi-backend            
Source: python-cffi 
Priority: optional  
Section: python     
Installed-Size: 205 
Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: amd64 
Version: 1.10.0-0.1+ubuntu14.04.1+certbot+1                                     
Replaces: python-cffi (<< 1)            
Provides: python-cffi-backend-api-9729, python-cffi-backend-api-max, python-cffi-backend-api-min
Depends: python (<< 2.8), python (>= 2.7~), libc6 (>= 2.14), libffi6 (>= 3.0.4) 
Breaks: python-cffi (<< 1)              
Filename: pool/main/p/python-cffi/python-cffi-backend_1.10.0-0.1+ubuntu14.04.1+certbot+1_amd64.deb
Size: 70120         
MD5sum: 6674a0210caf8e78a2f0225ded17ab9e                                        
SHA1: 91777768c26ff9fefd058115f669a75519ec25dc                                  
SHA256: d21a8b2a4b0ce0015601a5d57b11cc15465274b53662e0c590bdf713d445591a        
Description-en: Foreign Function Interface for Python calling C code - backend  
 Convenient and reliable way of calling C code from Python.                     
 .                  
 The aim of this project is to provide a convenient and reliable way of calling 
 C code from Python. It keeps Python logic in Python, and minimises the C       
 required. It is able to work at either the C API or ABI level, unlike most     
 other approaches, that only support the ABI level.                             
 .                  
 This package contains the runtime support for pre-built cffi modules.          
Description-md5: 48503c56f3120e90d31ebb94eea39999             
```

That does indeed fix it! 

@oerdnj Many thanks indeed!
