### ISSUE TITLE
certbot-auto traceback: AttributeError: 'Requirement' object has no attribute 'project_name'

### ISSUE THREAD

**Issue by kyrofa** [certbot/certbot#6781]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```
$ certbot-auto renew --standalone
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease              
Reading package lists... Done                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
libffi-dev is already the newest version (3.2.1-4).
augeas-lenses is already the newest version (1.4.0-0ubuntu1.1).
ca-certificates is already the newest version (20170717~16.04.2).
libaugeas0 is already the newest version (1.4.0-0ubuntu1.1).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.14).
openssl is already the newest version (1.0.2g-1ubuntu4.14).
python is already the newest version (2.7.12-1~16.04).
python-dev is already the newest version (2.7.12-1~16.04).
python-virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 153 not upgraded.
Creating virtual environment...
Installing Python packages...
Exception:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 600, in _prepare_file
    req_to_install.check_if_exists()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
Traceback (most recent call last):
  File "/tmp/tmp.NduBjZefFk/pipstrap.py", line 177, in <module>
    exit(main())
  File "/tmp/tmp.NduBjZefFk/pipstrap.py", line 164, in main
    shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U --no-cache-dir /tmp/pipstrap-oRyhtz/pip-9.0.1.tar.gz /tmp/pipstrap-oRyhtz/setuptools-40.6.3.zip /tmp/pipstrap-oRyhtz/wheel-0.29.0.tar.gz' returned non-zero exit status 2
```

## Certbot's behavior differed from what I expected because:
I expected it to work and not produce a traceback.

**Comment by ohemorange** [comment]
Looks to me like there's some version mismatch going on. What are the results when you run `pip --version` and `virtualenv --version`?

**Comment by ohemorange** [comment]
Also, what are the results of `source /opt/eff.org/certbot/venv/bin/activate && virtualenv --version && pip --version`?

**Comment by julianlam** [comment]
@ohemorange I currently experience the same issue as OP under the same OS.

```
# source /opt/eff.org/certbot/venv/bin/activate && virtualenv --version && pip --version
15.0.1
pip 8.1.1 from /opt/eff.org/certbot/venv/local/lib/python2.7/site-packages (python 2.7)
```

I do not have pip or virtualenv installed on my system apparently, so the first set of commands do not work (I just get a notice to install `python-pip` via apt)

**Comment by ohemorange** [comment]
@julianlam, were you always getting certbot from github, or were you previously using `dl.eff.org/certbot-auto`?

**Comment by ohemorange** [comment]
Ah, it looks like your version of `pip` is too old. Running `rm -rf /opt/eff.org/certbot/venv/` should resolve the issue, we'll look into why it's not being automatically upgraded.

**Comment by julianlam** [comment]
Hi @ohemorange -- as I initially set up LE during the beta, I've always had it pulling from GitHub:

`# git clone https://github.com/certbot/certbot.git /opt/letsencrypt`

... now of course, there might be a better way to do this :smile:

At any rate, unfortunately deleting that directory and re-running `./letsencrypt-auto certificates` returns the same error as above `AttributeError: 'Requirement' object has no attribute 'project_name'`

**Comment by kyrofa** [comment]
I'm using certbot-auto from https://dl.eff.org/certbot-auto. And indeed, deleting the venv (`rm -rf /opt/eff.org`) doesn't solve anything.

**Comment by ikeamanual** [comment]
I have the same error as OP,
also all the same --versions

Just a few more days until certificate expires...

**Comment by julianlam** [comment]
@ikeamanual nothing quite like a ticking clock eh?

**Comment by ohemorange** [comment]
Well, it's not quite a ticking clock -- anyone currently using certbot-auto on Ubuntu 16.04 can follow our official instructions [here](https://certbot.eff.org/) (select Ubuntu 16.04 from the dropdown), which should give a working version of certbot.

**Comment by ohemorange** [comment]
Wait, have you all been using it since getting it from github was the official way to get it? That version of `letsencrypt-auto` doesn't auto-update. What does `letsencrypt-auto --version` say? If it's not `0.31.0`, I *highly* recommend switching over to the official instructions (again, [here](https://certbot.eff.org)).

**Comment by julianlam** [comment]
No, at least, not for me. Whenever we spin up a new instance of our service we have it check out the latest version from GitHub. It's been auto-updating for awhile now.

**Comment by ohemorange** [comment]
Any chance you could check if it works when you use the official download way? I'd love to know if there's at least a backup option available for people with expiring certificates.

**Comment by julianlam** [comment]
@ohemorange That just what I was doing, and of course, it worked without a hitch. I suppose now I'll have to go and update the way we spin up our instances. Cheers!

**Comment by ohemorange** [comment]
That's great to hear, thanks for checking!

**Comment by kyrofa** [comment]
> [...] anyone currently using certbot-auto on Ubuntu 16.04 can follow our official instructions [...]

Indeed, the PPA is how I got around this issue.

**Comment by kyrofa** [comment]
> Wait, have you all been using it since getting it from github was the official way to get it?

No, I followed the docs [here](https://certbot.eff.org/docs/install.html#certbot-auto), which gets certbot-auto from https://dl.eff.org/certbot-auto

**Comment by mohammadaltaleb** [comment]
@ohemorange  I have the same issue.
Ubuntu 16.04.1, pip 8.1.1 and virtualenv 15.0.1.
It works after reinstalling pip which is so weird because I install the same version of pip.
The exception reappear after instance restart which is done daily in my case.

**Comment by ohemorange** [comment]
@mohammadaltaleb any chance you could post your logs, or email them to erica@eff.org? they're in `/var/log/letsencrypt`.

**Comment by mohammadaltaleb** [comment]
@ohemorange  I've sent a copy of the log directory.
