### ISSUE TITLE
Renewer fails to save and restore CLI config data types properly

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#893]
One has to manually specify data type conversions in order for renewer to work properly otherwise it leads to very cryptic errors, e.g. https://github.com/kuba/letsencrypt/commit/ed70c948aaad5d56835eecd7e7a77fd4ba87ca88 and build error https://travis-ci.org/kuba/letsencrypt/jobs/83587905#L2895.

3rd party plugins might register arbitrary CLI flags, so we must not hardcode all conversions!

**Comment by pde** [comment]
Current status: this is somewhat addressed by various terrible hacks, such as casting the strings "True", "False", and "None" back to their pythonic original types.

**Comment by bmw** [comment]
I still want to see this done as we still don't convert types properly, however, our current system works for all current flags and known 3rd party plugins.

**Comment by bmw** [comment]
This is coming back to bite us with #4105 as `pref_challs` is a list of challenge types and gets stored like:
```
pref_challs = <class 'acme.challenges.HTTP01'>
```

**Comment by bmw** [comment]
This is still a real issue.
