### ISSUE TITLE
Deploy hook scripts not executed on new SSL certificate issuance

### ISSUE THREAD

**Issue by nuxwin** [certbot/certbot#9978]
## My operating system is (include version):

```bash
nuxwin@smtp:/srv/i-hms-services/compose/letsencrypt$ hostnamectl 
 Static hostname: smtp
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: 70bcfc6e34454b32b22dadf2dc35bf99
         Boot ID: 56fbd2eaf9e74c4281d3117c7963d2d6
  Virtualization: kvm
Operating System: Debian GNU/Linux 12 (bookworm)              
          Kernel: Linux 6.1.0-23-amd64
    Architecture: x86-64
 Hardware Vendor: QEMU
  Hardware Model: Standard PC _i440FX + PIIX, 1996_
Firmware Version: rel-1.16.3-0-ga6ed6b701f0a-prebuilt.qemu.org
```

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

I run cerbot through a rebuilded Docker image (add Docker CLI support into it as all my services are run through Docker. This make me able to execute commands in Docker containers from the Certbot container). See the provided Dockerfile below.

The Cerbot version is:

```shell
nuxwin@smtp:/srv/i-hms-services/compose/letsencrypt$ docker run --rm i-hms/certbot certbot --version
certbot 2.11.0
```

The Docker version is:

```shell
$ docker version
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:19 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:19 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## I ran this command and it produced this output:

```shell
docker run \
  --rm \
  -ti \
  --name i-hms.acme \
  --network i-hms.network \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /srv/i-hms-services/compose/letsencrypt/docker-data/letsencrypt/production:/etc/letsencrypt \
  -v /srv/i-hms-services/compose/letsencrypt/docker-data/letsencrypt/production/logs:/var/log/letsencrypt \
  -v /srv/i-hms-services/compose/letsencrypt/docker-data/letsencrypt/ovh.ini:/root/.secrets/certbot/ovh.ini \
  -v /srv/i-hms-services/compose/haproxy/docker-data/haproxy:/usr/local/etc/haproxy \
  i-hms/certbot certonly \
  --dns-ovh \
  --dns-ovh-credentials ~/.secrets/certbot/ovh.ini \
  --dns-ovh-propagation-seconds 60 \
  --domain agon-partners-innovation.ch \
  --domain www.agon-partners-innovation.ch \
  --cert-name agon-partners-innovation.ch \
  --non-interactive \
  --agree-tos \
  --email l.declercq@i-hms.net \
  --expand \
  --non-interactive \
  --logs-dir /var/log/letsencrypt
```

```shell
...
2024-07-30 21:17:53,214:DEBUG:certbot._internal.display.obj:Notifying user:
Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/agon-partners-innovation.ch/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/agon-partners-innovation.ch/privkey.pem
This certificate expires on 2024-10-28.
These files will be updated when the certificate renews.
2024-07-30 21:17:53,215:DEBUG:certbot._internal.display.obj:Notifying user: NEXT STEPS:
2024-07-30 21:17:53,215:DEBUG:certbot._internal.display.obj:Notifying user: - The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you m>
2024-07-30 21:17:53,215:DEBUG:certbot._internal.display.obj:Notifying user: If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
```

As you can see here, the deploy hook scripts from the /etc/letsencrypt/renewal-hooks/deploy directory are not executed for new SSL certificate.

But, If I add both the `--dry-run` and `--run-deploy-hooks` options:

```shell
docker run \
  --rm \
  -ti \
  --name i-hms.acme \
  --network i-hms.network \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /srv/i-hms-services/compose/letsencrypt/docker-data/letsencrypt/production:/etc/letsencrypt \
  -v /srv/i-hms-services/compose/letsencrypt/docker-data/letsencrypt/production/logs:/var/log/letsencrypt \
  -v /srv/i-hms-services/compose/letsencrypt/docker-data/letsencrypt/ovh.ini:/root/.secrets/certbot/ovh.ini \
  -v /srv/i-hms-services/compose/haproxy/docker-data/haproxy:/usr/local/etc/haproxy \
  i-hms/certbot certonly \
  --dns-ovh \
  --dns-ovh-credentials ~/.secrets/certbot/ovh.ini \
  --dns-ovh-propagation-seconds 60 \
  --domain agon-partners-innovation.ch \
  --domain www.agon-partners-innovation.ch \
  --cert-name agon-partners-innovation.ch \
  --non-interactive \
  --agree-tos \
  --email l.declercq@i-hms.net \
  --expand \
  --non-interactive \
  --logs-dir /var/log/letsencrypt \
  --dry-run \
  --run-deploy-hooks
```

The deploy hook script are executed as expected :

```shell
...
2024-07-30 22:12:01,029:DEBUG:acme.client:Storing nonce: vGrHSb6c55wQbDxrU6vP2dZH51_aXcho25em6R275YeeVlMxdW8
2024-07-30 22:12:01,030:DEBUG:certbot._internal.renewal:Dry run: skipping updating lineage at /etc/letsencrypt/live/agon-partners-innovation.ch
2024-07-30 22:12:01,030:INFO:certbot.compat.misc:Running deploy-hook command: /etc/letsencrypt/renewal-hooks/deploy/dovecot
2024-07-30 22:12:01,177:DEBUG:certbot._internal.display.obj:Notifying user: Hook 'deploy-hook' ran with output:
 dovecot: signalled
2024-07-30 22:12:01,177:INFO:certbot.compat.misc:Running deploy-hook command: /etc/letsencrypt/renewal-hooks/deploy/haproxy
2024-07-30 22:12:01,341:DEBUG:certbot._internal.display.obj:Notifying user: Hook 'deploy-hook' ran with output:
 Generating the HAProxy /usr/local/etc/haproxy/certs/agon-partners-innovation.ch.pem file for the agon-partners-innovation.ch SSL certificate.
 Adding the HAProxy /usr/local/etc/haproxy/certs/agon-partners-innovation.ch.pem file for the agon-partners-innovation.ch www.agon-partners-innovation.ch domains in the /usr/local/etc/haproxy/crt-list.txt file.
 New empty certificate store '/usr/local/etc/haproxy/certs/agon-partners-innovation.ch.pem'!

 Transaction created for certificate /usr/local/etc/haproxy/certs/agon-partners-innovation.ch.pem!

 Committing /usr/local/etc/haproxy/certs/agon-partners-innovation.ch.pem
 Success!

 Inserting certificate '/usr/local/etc/haproxy/certs/agon-partners-innovation.ch.pem' in crt-list '/usr/local/etc/haproxy/crt-list.txt'..
 Success!
2024-07-30 22:12:01,341:INFO:certbot.compat.misc:Running deploy-hook command: /etc/letsencrypt/renewal-hooks/deploy/postfix
2024-07-30 22:12:01,483:DEBUG:certbot._internal.display.obj:Notifying user: Hook 'deploy-hook' ran with output:
 postfix: signalled
2024-07-30 22:12:01,483:DEBUG:certbot._internal.display.obj:Notifying user: The dry run was successful.
```

## Certbot's behavior differed from what I expected because:

For me, the deploy hook script should be run even for new SSL certificates, or there should be at least an option to get that behavior. My haproxy deploy hook script is able to install/update SSL certificates by consuming the HAProxy runtime API. It is as follows:

```shell
#!/bin/sh
#
# Script to deploy Let's Encrypt SSL certificates to HAProxy without reload.
#
# This script consume the HAProxy runtime API. It ensures that HAProxy can
# dynamically install/update SSL certificates without downtime, providing a more
# robust and seamless service.
# See https://www.haproxy.com/blog/dynamic-ssl-certificate-storage-in-haproxy
#
# Author: Laurent DECLERCQ, AGON PARTNERS INNOVATION <l.declercq@konzeptplus.ch>
# Version: 20240729

# Extract lineage and file paths from the Let's Encrypt environment variables.
LINEAGE_NAME=$(basename "${RENEWED_LINEAGE}")
FULLCHAIN_PATH="${RENEWED_LINEAGE}/fullchain.pem"
PRIVATE_KEY_PATH="${RENEWED_LINEAGE}/privkey.pem"

# Define HAProxy related variables.
HAPROXY_CONTAINER_NAME=${HAPROXY_CONTAINER_NAME:-i-hms.haproxy}
HAPROXY_CONFIG_DIR=${HAPROXY_CONFIG_DIR:-/usr/local/etc/haproxy}
HAPROXY_RUNTIME_API_SOCK_PATH=${HAPROXY_RUNTIME_API_SOCK_PATH:-/var/run/haproxy/haproxy_api.sock}
HAPROXY_SSL_CERTIFICATE_PATH="${HAPROXY_CONFIG_DIR}/certs/${LINEAGE_NAME}.pem"
HAPROXY_SSL_CRT_LIST_FILE_PATH="${HAPROXY_CONFIG_DIR}/crt-list.txt"

# Function to upload an in-memory SSL certificate using HAProxy runtime API.
upload_in_memory_cert() {
  # Start a new transation to set the SSL certificate.
  docker exec "${HAPROXY_CONTAINER_NAME}" bash -c "echo -e \"set ssl cert ${HAPROXY_SSL_CERTIFICATE_PATH} <<\n\$(cat ${HAPROXY_SSL_CERTIFICATE_PATH})\n\" | socat - UNIX-CONNECT:${HAPROXY_RUNTIME_API_SOCK_PATH}"
  # Commit the SSL certificate.
  docker exec "${HAPROXY_CONTAINER_NAME}" bash -c "echo -e \"commit ssl cert ${HAPROXY_SSL_CERTIFICATE_PATH}\" | socat - UNIX-CONNECT:${HAPROXY_RUNTIME_API_SOCK_PATH}"
}

# Function to create a new in-memory SSL certificate using HAProxy runtime API.
create_in_memory_cert() {
  # Create a new HAProxy slot for the in-memory SSL certificate.
  docker exec "${HAPROXY_CONTAINER_NAME}" bash -c "echo -e \"new ssl cert ${HAPROXY_SSL_CERTIFICATE_PATH}\" | socat - UNIX-CONNECT:${HAPROXY_RUNTIME_API_SOCK_PATH}"
  # Upload the in-memory SSL certificate.
  upload_in_memory_cert
  # Add the SSL certificate to the in-memory crt-list file.
  docker exec "${HAPROXY_CONTAINER_NAME}" bash -c "echo -e \"add ssl crt-list ${HAPROXY_SSL_CRT_LIST_FILE_PATH} <<\n${HAPROXY_SSL_CERTIFICATE_PATH}\n\" | socat - UNIX-CONNECT:${HAPROXY_RUNTIME_API_SOCK_PATH}"
}

# Ensure that both the fullchain and private key files exist.
if [ -f "${FULLCHAIN_PATH}" ] && [ -f "${PRIVATE_KEY_PATH}" ]; then
  echo "Generating the HAProxy ${HAPROXY_SSL_CERTIFICATE_PATH} file for the ${LINEAGE_NAME} SSL certificate."

  cat "${FULLCHAIN_PATH}" "${PRIVATE_KEY_PATH}" > "${HAPROXY_SSL_CERTIFICATE_PATH}"

  echo "Adding the HAProxy ${HAPROXY_SSL_CERTIFICATE_PATH} file for the ${RENEWED_DOMAINS} domains in the ${HAPROXY_SSL_CRT_LIST_FILE_PATH} file."

  # Check if the certificate entry already exists in the crt-list file.
  if grep -Eq "^$(echo "${HAPROXY_SSL_CERTIFICATE_PATH}" | sed 's/[.[\^$*+?(){|]/\\&/g')$" "${HAPROXY_SSL_CRT_LIST_FILE_PATH}"; then
    echo "Entry already exists in the HAProxy ${HAPROXY_SSL_CRT_LIST_FILE_PATH} crt-list file. Updating the in-memory SSL certificate..."
    upload_in_memory_cert
  else
    echo "${HAPROXY_SSL_CERTIFICATE_PATH}" >> "${HAPROXY_SSL_CRT_LIST_FILE_PATH}"
    create_in_memory_cert
  fi
else
  echo "Couldn't build the HAProxy ${HAPROXY_SSL_CERTIFICATE_PATH} file for the ${LINEAGE_NAME} SSL certificate: SSL material not found."
fi
```

## My Dockerfile to rebuild the Docker certbot image:

```Dockerfile
# Docker image to add Docker cli to the certbot/certbot image.
#
# You can build the image as follows:
#
# - docker build --progress plain --no-cache --pull --tag i-hms/certbot:latest .
#
# Author: Laurent DECLERCQ, AGON PARTNERS INNOVATION ag <l.declercq@konzeptplus.ch>
# Version: 20240728

# Make use of the official certbot/certbot image as the base.
#FROM certbot/certbot:latest
FROM certbot/dns-ovh:latest

VOLUME /var/run/docker.sock

# Install the required packages for the Docker CLI installation
# Install the Docker CLI from the official Docker source.
RUN apk add --no-cache --virtual .build-deps \
     curl \
  && curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-27.1.1.tgz | tar -xz --strip-components=1 -C /usr/local/bin docker/docker \
  && apk del .build-deps

# Disable default entrypoint so arguments to docker run will exec as a shell form CMD.
ENTRYPOINT []
```

**Comment by nuxwin** [comment]
Looking at code, it seem that deploy hook scripts are never executed on new SSL certificate issuance, and that seem to be the expected behavior by the developers. However, adding an option to execute them could be beneficial for some of us as the use case shown in my first post. My HAProxy is configured in dynamic way. Thanks.

**Comment by skupfer** [comment]
Pretty sure you can use the hook commands `--pre-hook script`, `--deploy-hook script` and `--post-hook script` with `certonly`. I guess this is by intention because on a new certificate it's expected that nothing blocks the port or even needs a restart because e.g. nginx/haproxy would throw an error anyways trying to start them without a certificate. Even if somethings blocks the port you could use the `--http-01-port` challenge. On renewal the hooks run as expected. If your application is running already, you have to explicitly tell certbot to run the hooks on a new certificate request.

**Comment by nuxwin** [comment]
@skupfer my HAProxy is dynamic in this regard...

Regarding SSL cert issuance, nothing is blocking ... requests are passed through my HAProxy to the certbot container on port 8889 which is resolved at runtime.

```
global
  log stdout format raw local0 info

  stats socket /var/run/haproxy/haproxy_api.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
  stats timeout 30s

  # Base directories for SSL material.
  ca-base /etc/ssl/certs
  crt-base /etc/ssl/private

  # Restrict SSL version.
  ssl-default-bind-options ssl-min-ver TLSv1.2 prefer-client-ciphers no-tls-tickets
  ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:@SECLEVEL=2
  ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384::@SECLEVEL=2:!aNULL:!MD5:!DSS:!SHA1:!AESCCM

  tune.ssl.default-dh-param 2048

defaults
  log global

  mode http

  option httpslog
  option dontlognull
  #option http-server-close
  option http-keep-alive
  option forwardfor except 127.0.0.0/8
  option redispatch

  retries 3

  timeout http-request 10s
  timeout queue 1m
  timeout connect 10s
  timeout client 1m
  timeout server 1m
  timeout http-keep-alive 10s
  timeout check 10s

  maxconn 3000
#  errorfile 400 /usr/local/etc/haproxy/errors/400.http
#  errorfile 403 /usr/local/etc/haproxy/errors/403.http
#  errorfile 408 /usr/local/etc/haproxy/errors/408.http
#  errorfile 500 /usr/local/etc/haproxy/errors/500.http
#  errorfile 502 /usr/local/etc/haproxy/errors/502.http
#  errorfile 503 /usr/local/etc/haproxy/errors/503.http
#  errorfile 504 /usr/local/etc/haproxy/errors/504.http

  # Never fail on address resolution
  # Since our backend reference Docker service names, those must be resolved at runtime.
  # That why we set init-addr to "none" which mean that HAProxy can start without
  # resolving the names with the expectation that they will be resolved later at runtime.
  default-server init-addr none

# Define resolver
resolvers docker_dns_resolver
  # We make use of internal docker DNS resolver which aims to resolve service names within Docker network.
  # Docker DNS-based service discovery for DNS population.
  nameserver ns1 127.0.0.11:53
  # Maximum size of a DNS anser allowed, in bytes.
  accepted_payload_size 512
  # Whether to add nameservers found in /etc/resolv.conf file.
  #parse-resolv-conf
  # How long to "hold" a backend server's up/down status depending on the name resolution status.
  # For example, if an NXDOMAIN response is returned, keep the backend server in its current state (up) for
  # at least another 30 seconds before marking it as down due to DNS not having a record for it.
  hold valid 10s
  hold other 30s
  hold refused 30s
  hold nx 30s
  hold timeout 30s
  hold obsolete 30s
  # How many time to retry a query.
  resolve_retries 3
  # how long to wait between retries when no valid response has been received.
  timeout retry 1s
  # How long to wait for a successful resolution.
  timeout resolve 1s

frontend health
  mode http
  bind 127.0.0.1:80
  http-request return status 200 if { src 127.0.0.0/8 }

# Frontend to handle both HTTP and HTTPS requests.
frontend traffic-in-80-443
  # Listen on standard 80 port for HTTP requests.
  bind *:80

  # Listen on standard 443 port for HTTPS requests.
  # Appropriate SSL certificate is retrieved using map (SSL cert path => domain name).
  bind *:443 ssl crt-list /usr/local/etc/haproxy/crt-list.txt alpn h2,http/1.1,http/1.0

  # Redirect non-HTTPS to HTTPS.
  http-request redirect scheme https code 301 unless { ssl_fc }

  # Enables the insertion of the client's IP address into the HTTP header of the backend request.
  option forwardfor

  # Specifies the name of the header where the client's IP address will be inserted
  option forwardfor header X-Real-IP

  http-request add-header X-Real-IP %[src]
  http-request add-header X-Forwarded-Proto https if { ssl_fc  }
  http-request add-header X-Forwarded-Proto http if !{ ssl_fc }
  http-request set-header X-Forwarded-For %[src]
  http-request set-header X-Forwarded-Host %[req.hdr(Host)]

  # Sets up HSTS (Strict Transport Security header)  
  http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" if { ssl_fc }

  # Sets up server name (we do not want expose underlying server names).
  http-after-response set-header Server "i-HMS Traffic Director/Balancer v1.0.1 <l.declercq@i-hms.net>"

  # Sets up an ACL for the ACME challenge requests (LetsEncrypt).
  acl acme_challenge path_beg /.well-known/acme-challenge/

  # Sets up an ACL for the webmail requests (Roundcube).
  acl host_roundcube_webmail hdr(host) -i webmail.i-hms.net

  # Sets up an ACL for agon-partners-innovation (proxy).
  acl host_agon_partners_innovation hdr(host) -i www.agon-partners-innovation.ch agon-partners-innovation.ch www.agon-partners-innovation.com agon-partners-innovation.com

  # Uses the acme-challenge-backend backend for the ACME challenge requests (LetsEncrypt).
  use_backend acme-challenge-backend if acme_challenge

  # Uses the roundcube-webmail-backend backend for the webmail requests (Roundcube).
  use_backend roundcube-webmail-backend if host_roundcube_webmail

  # Uses the konzeptplus-backend for the agon-partners-innovation site (proxy).
  use_backend konzeptplus-backend if host_agon_partners_innovation

  # Sets default backend for uknown hosts.
  default_backend unknown-hosts-backend

# Stats access (non standard port, basic authentication).
listen haproxy-stats
  bind *:8888 ssl crt-list /usr/local/etc/haproxy/crt-list.txt
  stats enable
  stats hide-version
  stats refresh 1s
  stats show-node
  stats auth user:password
  stats uri /

# Default backend for unknown hosts.
backend unknown-hosts-backend
  http-request return status 404 content-type text/plain string "Unknown Host. Please contact the system administrator."

# Backend for the ACME challenges requests (LetsEncrypt).
backend acme-challenge-backend
  server acme-challenge-server i-hms.acme:8889 resolvers docker_dns_resolver resolve-prefer ipv4

# Backend for the webmail requests (Roundcube).
backend roundcube-webmail-backend
  server roundcube-webmail-server i-hms.roundcube.nginx:80 check resolvers docker_dns_resolver resolve-prefer ipv4

# Backend for the agon-partners-innovation (proxy)
backend konzeptplus-backend
  mode http
  http-request set-header Host konzeptplus.ch
  server konzeptplus-server konzeptplus.ch:443 resolvers docker_dns_resolver resolve-prefer ipv4 sni req.hdr(host) ssl verify none check
```

I don't use the cli options for the hooks through. I use the hook directories.

**Comment by ohemorange** [comment]
The hook directories (and the deploy hook more generally) are built to work with certbot's renewal infrastructure, which automatically renews certs for you. You can switch to using the `renew` verb (instead of `certonly`) to access the directories.

If you'd prefer to keep using `certonly`, you can specify `--deploy-hook` on the cli.

Is there a reason neither of these options will work for you?

**Comment by alexmv** [comment]
This issue persists on 5.1.0 -- #10146 did nothing to change it.

I can't speak for the OP, but our use case is that we have an nginx with a temporary self-signed certificate, which is also used to serve a webroot http challenge.  We'd like to run all of our standard backup-the-new-cert and restart-services hooks when we get the initial certificate, because the behaviour we need is identical to when we get a renewed Lets Encrypt certificate.

---

> The hook directories (and the deploy hook more generally) are built to work with certbot's renewal infrastructure, which automatically renews certs for you. You can switch to using the renew verb (instead of certonly) to access the directories.

`renew` does not work if you're initially obtaining a _new_ certificate, which is what this issue is about.

> If you'd prefer to keep using `certonly`, you can specify `--deploy-hook` on the cli.

This allows specifying _one_ hook file to run.
